name: Docker

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 5 * * 1'

jobs:
  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Fetch LFS objects
        run: git lfs checkout
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set cache parameters
        id: cache-outputs
        run: |
          if [ "${{ github.run_attempt }}" -eq "1" ]; then
            echo cache-from="type=gha" >> "$GITHUB_OUTPUT"
          else
            echo cache-from= >> "$GITHUB_OUTPUT"
          fi
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          cache-to: type=gha,mode=max
          cache-from: ${{ steps.cache-outputs.outputs.cache-from }}
          tags: ride_along
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ride_along
          trivy-config: trivy.yml
